#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
# Copyright Gen Digital Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: login-consent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-consent
  template:
    metadata:
      labels:
        app: login-consent
    spec:
      volumes:
        - name: config
          configMap:
            name: login-consent-claims-config
      containers:
      - name: login-consent
        envFrom:
          - configMapRef:
              name: login-consent-env
        image: login-consent-server:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
        volumeMounts:
          - name: config
            mountPath: /etc/login-consent/config
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: login-consent
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: login-consent
status:
  loadBalancer: {}
