#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Job
apiVersion: batch/v1
metadata:
  name: hydra-create-client
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: healthcheck-ready
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              while [[ "$(wget -T 5 -S --spider http://hydra-admin/health/ready 2>&1 | grep '200 OK')" == "" ]];
              do echo "waiting for endpoint";
              sleep 5;
              done;
      containers:
      - name: hydra-clients-create
        image: "oryd/hydra:v1.3.2-alpine"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            echo "Creating clients ...";

            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id auth-code-client --name "Share Your Credentials" --secret secret --grant-types authorization_code,refresh_token --response-types code,id_token --scope StudentCard,TravelCard,PermanentResidentCard,VaccinationCertificate,CertifiedMillTestReport,CrudeProductCredential,UniversityDegreeCredential,CreditCardStatement,mDL,CreditScore --skip-tls-verify --callbacks https://demo-issuer.||DOMAIN||/callback 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;

            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id bank_issuer --name "bank_issuer" --secret bank-issuer-secret --grant-types authorization_code --response-types code --scope openid,profile,address,BankAccountProof --skip-tls-verify --callbacks https://api-gateway.||DOMAIN||/oidc/redirect 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;
            
            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id pr_card_issuer_jwtsd --name "pr_card_issuer_jwtsd" --secret pr-card-issuer-jwtsd-secret --grant-types authorization_code --response-types code --scope openid,profile,address,PRCardProof --skip-tls-verify --callbacks https://api-gateway.||DOMAIN||/oidc/redirect 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;
            
            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id vaccination_certificate_issuer --name "vaccination_certificate_issuer" --secret vaccination-certificate-issuer-secret --grant-types authorization_code --response-types code --scope openid,profile,address,VaccinationCertificateProof --skip-tls-verify --callbacks https://api-gateway.||DOMAIN||/oidc/redirect 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;

            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id utopian_customs_and_immigration_issuer --name "utopian_customs_and_immigration_issuer" --secret utopian-customs-and-immigration-issuer-secret --grant-types authorization_code --response-types code --scope openid,profile,address,PRCardProof --skip-tls-verify --callbacks https://api-gateway.||DOMAIN||/oidc/redirect 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;

            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id true_id_issuer --name "true_id_issuer" --secret true-id-issuer-secret --grant-types authorization_code --response-types code --scope openid,profile,address,TrueIdentityProof --skip-tls-verify --callbacks https://api-gateway.||DOMAIN||/oidc/redirect 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;
            
            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id university_degree_issuer_bbs --name "university_degree_issuer_bbs" --secret university-degree-issuer-bbs-secret --grant-types authorization_code --response-types code --scope openid,profile,address,UniversityDegreeProof --skip-tls-verify --callbacks https://api-gateway.||DOMAIN||/vcs-localkms/oidc/redirect 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; break;else exit 1;fi;

            err_resp=$(hydra clients create --endpoint http://hydra-admin --fake-tls-termination --id hub-auth --secret hub-auth-secret --grant-types authorization_code,refresh_token --response-types code,id_token --scope openid,profile,email --skip-tls-verify --callbacks https://hub-auth.||DOMAIN||/oidc/callback 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "Success client creation"; exit 0;else exit 1;fi;
            echo "... Finished creating clients"
